WebScrapper/Scrapper/Scrapper/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

WebScrapper/Scrapper/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#Template tagging
app_name = "basic_app"

urlpatterns = [
    url(r'relative/$',views.relative,name='relative'),
    url(r'amazon/$',views.amazon,name='amazon'),
    url(r'bestbuy/$',views.bestbuy,name='bestbuy'),
    url(r'ebay/$',views.ebay,name='ebay'),
    url(r'google/$',views.google,name='google'),
    url(r'yahoo/$',views.yahoo,name='yahoo'),
]

WebScrapper/Scrapper/basic_app/models.py
from django.db import models

# Create your models here.

WebScrapper/Scrapper/basic_app/forms.py
from django import forms

class FormName_amazon(forms.Form):
    AmazonProductCode = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'E.g. B01LYHL9YY'}),label='Amazon ASIN Code')

class FormName_bestbuy(forms.Form):
    BestBuyProductCode = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'E.g. 5835851'}),label='BestBuy Product ID')

class FormName_ebay(forms.Form):
    EbayProductCode = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'E.g. 110891711'}),label='Ebay Item No.')

class FormName_google(forms.Form):
    GoogleCompanyTicker = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'E.g. MSFT,GE'}),label='Google Finance Company Code')
    StartDay = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'1 - 31'}),label='Start Day')
    StartMonth = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'1 - 12'}),label='Start Month')
    StartYear = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'from 1970 to present'}),label='Start Year')
    EndDay = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'1 - 31'}),label='End Day')
    EndMonth = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'1 - 12'}),label='End Month')
    EndYear = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'from 1970 to present'}),label='End Year')

    def clean(self):
        all_clean_data = super().clean()
        StartDay = all_clean_data['StartDay']
        StartMonth = all_clean_data['StartMonth']
        StartYear = all_clean_data['StartYear']
        EndDay = all_clean_data['EndDay']
        EndMonth = all_clean_data['EndMonth']
        EndYear = all_clean_data['EndYear']

        if int(StartDay)<1 or int(StartDay)>31:
            raise forms.ValidationError("MAKE SURE START DATE IS A VALID ONE")
        if int(StartMonth)<1 or int(StartMonth)>12:
            raise forms.ValidationError("MAKE SURE START MONTH IS A VALID ONE")
        if int(EndDay)<1 or int(EndDay)>31:
            raise forms.ValidationError("MAKE SURE END MONTH IS A VALID ONE")
        if int(EndMonth)<1 or int(EndMonth)>12:
            raise forms.ValidationError("MAKE SURE END YEAR IS A VALID ONE")
        if int(StartYear)>=int(EndYear):
            raise forms.ValidationError("START YEAR AND END YEAR HAS TO BE DIFFERENT")

class FormName_yahoo(forms.Form):
    YahooCompanyTicker = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'E.g. MSFT,GE'}),label='Yahoo Finance Company Code')
    StartDay = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'1 - 31'}),label='Start Day')
    StartMonth = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'1 - 12'}),label='Start Month')
    StartYear = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'from 1970 to present'}),label='Start Year')
    EndDay = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'1 - 31'}),label='End Day')
    EndMonth = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'1 - 12'}),label='End Month')
    EndYear = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'from 1970 to present'}),label='End Year')

    def clean(self):
        all_clean_data = super().clean()
        StartDay = all_clean_data['StartDay']
        StartMonth = all_clean_data['StartMonth']
        StartYear = all_clean_data['StartYear']
        EndDay = all_clean_data['EndDay']
        EndMonth = all_clean_data['EndMonth']
        EndYear = all_clean_data['EndYear']

        if int(StartDay)<1 or int(StartDay)>31:
            raise forms.ValidationError("MAKE SURE START DATE IS A VALID ONE")
        if int(StartMonth)<1 or int(StartMonth)>12:
            raise forms.ValidationError("MAKE SURE START MONTH IS A VALID ONE")
        if int(EndDay)<1 or int(EndDay)>31:
            raise forms.ValidationError("MAKE SURE END MONTH IS A VALID ONE")
        if int(EndMonth)<1 or int(EndMonth)>12:
            raise forms.ValidationError("MAKE SURE END YEAR IS A VALID ONE")
        if int(StartYear)>=int(EndYear):
            print ("start year "+StartYear+" end year "+EndYear)
            raise forms.ValidationError("START YEAR AND END YEAR HAS TO BE DIFFERENT")

WebScrapper/Scrapper/basic_app/views.py
from django.shortcuts import render
from basic_app import forms
from django.http import *
import csv
from bs4 import BeautifulSoup
import requests
import re
from time import sleep
import multiprocessing
import glob
from tkinter import *
import re
import time
import datetime
import urllib.request
import bs4 as bs
import xlsxwriter
import math
import os
from pyexcel.cookbook import merge_all_to_a_book

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def google(request):
    form4 = forms.FormName_google()
    if request.method == 'POST':
        form4 = forms.FormName_google(request.POST)

        if form4.is_valid():
            print("validation success")
            TICKER = form4.cleaned_data["GoogleCompanyTicker"]
            STARTDATE = form4.cleaned_data["StartDay"]
            STARTMONTH = form4.cleaned_data["StartMonth"]
            STARTYEAR = form4.cleaned_data["StartYear"]
            ENDDAY = form4.cleaned_data["EndDay"]
            ENDMONTH = form4.cleaned_data["EndMonth"]
            ENDYEAR = form4.cleaned_data["EndYear"]
            response = StreamingHttpResponse(google_write(TICKER,STARTDATE,STARTMONTH,STARTYEAR,ENDDAY,ENDMONTH,ENDYEAR))
            return response
    return render(request, 'basic_app/Google.html',{'form4':form4})

def google_write(tckr,sd,sm,sy,ed,em,ey):

    '''sets the end and start dates from the text file to the values that would be used in the string and convert them to a string'''
    ticker = tckr.upper().strip()
    m1 = str(sm).strip()
    d1 = str(sd).strip()
    y1 = str(sy).strip()

    m2 = str(em).strip()
    d2 = str(ed).strip()
    y2 = str(ey).strip()
    start_date = ("{}/{}/{}".format(d1, m1, y1))
    print("start date is {}".format(start_date))
    end_date = ("{}/{}/{}".format(d2, m2, y2))
    # print("end date is {}".format(end_date))
    '''set the ticker value from the text file'''

    start_timestamp = time.mktime(datetime.datetime.strptime(start_date, "%d/%m/%Y").timetuple())
    end_timestamp = time.mktime(datetime.datetime.strptime(end_date, "%d/%m/%Y").timetuple())

    days = (end_timestamp - start_timestamp) / 86400
    effective_days = days * (5 / 7)
    pages = effective_days / 200
    print("timestamp difference {} days is {} and effective days is {} pages is{}".format((
        end_timestamp - start_timestamp), days, effective_days, math.ceil(pages)))

    no_of_pages = math.ceil(pages)

    list_count = 0
    split_nn_list = []
    xList = []
    month = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

    for page_count in range(0,no_of_pages,1):

        url1 = "https://finance.google.com/finance/historical?q=NASDAQ:"+ticker+"&startdate="+month[int(
         m1)-1]+"+"+d1+"%2C+"+y1+"&enddate="+month[int(
            m2)-1]+"+"+d2+"%2C+"+y2+"&num=200&ei=HV3FWauPPIi_jAHlsozoAQ&start="+str(page_count*200)
        a = urllib.request.urlopen(url1).read()

        soup = bs.BeautifulSoup(a,'html.parser')

        table = soup.find_all('table',{'class':'gf-table historical_price'})
        '''xList filters the data from the website and appends it in the form of a string'''
        for x in table:
            xList.append(x.text)
        print("page "+str(page_count)+" done")
        '''split_nn_list will hold the total array of data particular to each day, splitting on \n\n'''
        try:
            split_nn_list.append(xList[int(page_count)].split('\n\n'))
        except:
            pass

    '''this is to print all whole list of values for all the pages info gathered'''
    #print('split_nn_list is \n',split_nn_list)
    workbook = xlsxwriter.Workbook('C:/Users/vamshi/Desktop/DATA_EXTRACTION/google/'+ticker+'--Google Finance Data.xlsx')
    worksheet = workbook.add_worksheet()
    '''j = 1 for incrementing the counter for writing the data into rows of excel'''
    j=1
    for a in split_nn_list:
        for b in a:
            row_string = 'A' + str(j)
            '''indiv_list is the single row element consisting of all the data required to be put in the row'''
            indiv_list = b.split('\n')
            yield(b)
            worksheet.write_row(row_string,indiv_list)
            j = j+1
        '''reinitializing the row_string to be zero after each iteration '''
        row_string = ''
    workbook.close()

def yahoo(request):
    form5 = forms.FormName_yahoo()
    #verifying that its yahoo page that is being requested by forms.
    if request.method == 'POST':
        form5 = forms.FormName_yahoo(request.POST)

        #get the inputs from the html page to process and verify if validation was success
        if form5.is_valid():
            print("validation success")
            TICKER = form5.cleaned_data["YahooCompanyTicker"]
            STARTDATE = form5.cleaned_data["StartDay"]
            STARTMONTH = form5.cleaned_data["StartMonth"]
            STARTYEAR = form5.cleaned_data["StartYear"]
            ENDDAY = form5.cleaned_data["EndDay"]
            ENDMONTH = form5.cleaned_data["EndMonth"]
            ENDYEAR = form5.cleaned_data["EndYear"]
            response = StreamingHttpResponse(yahoo_write(TICKER,STARTDATE,STARTMONTH,STARTYEAR,ENDDAY,ENDMONTH,ENDYEAR))
            return response
    return render(request, 'basic_app/Yahoo.html',{'form5':form5})

def yahoo_write(tckr,sd,sm,sy,ed,em,ey):
    # set the ticker value from the file, strip and make everything into uppercase
    ticker = tckr.upper().strip()
    m1 = str(sm).strip()
    d1 = str(sd).strip()
    y1 = str(sy).strip()

    # sets the end and start dates from the render to the values that would be used in the string and convert them to a string
    m2 = str(em).strip()
    d2 = str(ed).strip()
    y2 = str(ey).strip()
    startdate = str(m1+"/"+d1+"/"+y1)
    enddate = str(m2+"/"+d2+"/"+y2)

    print (" start date is %s and type is %s " %(startdate,type(startdate)))
    print ("end date is %s and type is %s "%(enddate,type(enddate)))
    print("ticker is %s and type is %s" %(ticker,type(ticker)))

    # Timestamp value for startdate and enddate is the complete numerical representation of date, month and year
    # representation of date.
    timestamp_startdate = int(time.mktime(datetime.datetime.strptime(startdate, "%m/%d/%Y").timetuple()))
    timestamp_enddate = int(time.mktime(datetime.datetime.strptime(enddate, "%m/%d/%Y").timetuple()))
    timestamp_difference = int(timestamp_enddate) - int(timestamp_startdate)
    actual_end = (timestamp_enddate)
    actual_start = (timestamp_startdate)

    print("start time is ", int(timestamp_startdate))
    print("end time is ", int(timestamp_enddate))
    print("difference in timestamp is ", ((timestamp_enddate) - (timestamp_startdate)))
    # This is the value need to make it a shift by one day i.e. 24 hours in time stamp conversion.
    step = int(10540800)
    table_complete = []

    pool_input_list = []
    pool_input_tuple = ()
    j=0
    # The range starts from descending order from the last date to the date which comes by subtracting the one page
    # value of timestamp.
    for i in range(actual_start, actual_end, step):
        timestamp_startdate = timestamp_enddate - 10540800
        if (timestamp_startdate <= actual_start):
            timestamp_startdate = actual_start
        # Ticker name is company name in 2-4 letters is unique for every product, this needs to be changed to get value
        #  of each product.
        url_page = "https://finance.yahoo.com/quote/" + ticker + "/history?period1=" + str(
            timestamp_startdate) + "&period2=" + str(timestamp_enddate) + "&interval=1d&filter=history&frequency=1d"

        # Creates a list of URLs, one for each page. We can only do this if we get the total no. of pages in the previous
        #  step.
        pool_input_list.append([[j,url_page]])
        timestamp_enddate = timestamp_startdate - 86400
        j = j+1
    # All the pages are then appended into a list in the previous step and converted into a tuple.
    pool_input_tuple = tuple(pool_input_list)
    print(pool_input_tuple)

    # The multiprocessing process is initiated with a total number of processes as 4. The URLs and the URL numbers
    # are passed as a input.
    p = multiprocessing.Pool(processes=4)
    p.map(parsing_yahoo, pool_input_tuple)

    #This function is specific to excel sheets combining.
    merge_all_to_a_book(glob.glob("C:/Users/vamshi/Desktop/DATA_EXTRACTION/yahoo/"+str(ticker)+"/*.xlsx"), "C:/Users/vamshi/Desktop/DATA_EXTRACTION/yahoo/"+str(ticker)+"/Yahoo Data combined.xlsx")

    # All the files that were created per page are accessed and combined into a single Combined file.
    rd = glob.glob("C:/Users/vamshi/Desktop/DATA_EXTRACTION/yahoo/"+str(ticker)+"/*.txt")
    with  open("C:/Users/vamshi/Desktop/DATA_EXTRACTION/yahoo/"+str(ticker)+"/Yahoo Data combined.txt","wb") as outfile:
        for f in rd:
            with open(f, "rb") as infille:
                outfile.write(infille.read())

    # The single file is opened and all the lines are read, this is done to display the output to the screen.
    file = open("C:/Users/vamshi/Desktop/DATA_EXTRACTION/yahoo/"+str(ticker)+"/Yahoo Data combined.txt")
    lines = file.readlines()
    for line in lines:
        yield(line)
    file.close()


def parsing_yahoo(poolinput):
    # The last file name is obtained to get the name of the folder to be created using regular expressions.
    k = re.findall("[A-Z]+", poolinput[0][1])
    print("k is {}",k)
    table_complete=[]

    # Scraping process starts here
    for i in range(len(poolinput)):

        url = poolinput[i][1]
        print(poolinput[i][0])

        url1 = urllib.request.urlopen(url).read()

        soup = bs.BeautifulSoup(url1, 'html.parser')

        table = soup.find_all('tr')
        # append into table_complete the values after each iteration.
        table_complete.append(table)

WebScrapper/Scrapper/templates/basic_app/Amazon.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

  <div class="jumbotron">
    <h1>Welcome to Amazon data extraction</h1>
  </div>
  <form method="post">
    <div class="jumbotron">
      {{form1.as_p}}
      {% csrf_token %}
      <input type="submit" class="btn btn-success btn-lg" name="" value="ENTER">
    </div>
  </form>
  {% endblock %}

WebScrapper/Scrapper/templates/basic_app/Bestbuy.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

    <div class="jumbotron">
      <h1>Welcome to BestBuy data extraction</h1>
    </div>
    <form method="post">
      <div class="jumbotron">
        {{form2.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-success btn-lg" name="" value="ENTER">
      </div>
    </form>
  {% endblock %}

WebScrapper/Scrapper/templates/basic_app/Ebay.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

    <div class="jumbotron">
      <h1>Welcome to Ebay Data extraction</h1>
    </div>
    <form method="post">
      <div class="jumbotron">
        {{form3.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-success btn-lg" name="" value="ENTER">
      </div>
    </form>
  {% endblock %}

WebScrapper/Scrapper/templates/basic_app/Google.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

    <div class="jumbotron">
      <h1>Welcome to Google Data extraction</h1>
    </div>
      <form method="post" class="form-group">
        <div class="jumbotron" >
          {{form4.as_p}}
          {% csrf_token %}
          <input type="submit" class="btn btn-success btn-lg" name="" value="ENTER">
        </div>
      </form>
    </div>


  {% endblock %}

WebScrapper/Scrapper/templates/basic_app/Yahoo.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

      <div class="jumbotron">
        <h1>Welcome to Yahoo data extraction</h1>
      </div>
      <form method="post">
        <div class="jumbotron">
        {{form5.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-success btn-lg" name="" value="ENTER">
      </div>
    </form>
  {% endblock %}

WebScrapper/Scrapper/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">INDEX </a> </li>
          <li><a class="navbar-link" href="{% url 'basic_app:amazon' %}">AMAZON </a> </li>
          <li><a class="navbar-link" href="{% url 'basic_app:ebay' %}">EBAY </a> </li>
          <li><a class="navbar-link" href="{% url 'basic_app:bestbuy' %}">BESTBUY </a> </li>
          <li><a class="navbar-link" href="{% url 'basic_app:yahoo' %}">YAHOO </a> </li>
          <li><a class="navbar-link" href="{% url 'basic_app:google' %}">GOOGLE </a> </li>
        </ul>
      </div>

      <div class="container">
        {% block body_block %}
        {% endblock %}
      </div>
    </nav>
  </body>
</html>

WebScrapper/Scrapper/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

  <div class="jumbotron">
      <h1>THIS IS FROM INDEX PAGE</h1>
  </div>
  <div class="jumbotron">
      <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">lorem</a></p> -->
      <p>This page displays the sites it can scrape data from </p>
      <p>Links to the some of the example URL's are</p>
      <ul>
        <li><a href="http://www.amazon.com/product-reviews/B01LYHL9YY/ref=cm_cr_arp_d_paging_btm_2?ie=UTF8&reviewerType=all_reviews">AMAZON</a></li>
        <li><a href="https://www.bestbuy.com/site/reviews/s/5835851">BESTBUY</a></li>
        <li><a href="https://www.ebay.com/urw/product-reviews/110891711?_itm=1000047616&pgn=1">EBAY</a></li>
        <li><a href="https://finance.google.com/finance/historical?q=NASDAQ:MSFT&startdate=Dec+10%2C+2016&enddate=Dec+10%2C+2017&num=200&ei=HV3FWauPPIi_jAHlsozoAQ&start=0">GOOGLE</a></li>
        <li><a href="https://finance.yahoo.com/quote/MSFT/history?period1=1497243600&period2=1507784400&interval=1d&filter=history&frequency=1d">YAHOO</a></li>
      </ul>
  </div>

  {% endblock %}

WebScrapper/Scrapper/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>RELATIVE</title>
  </head>
  <body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'basic_app:amazon' %}">AMAZON</a>
    <a href="{% url 'basic_app:bestbuy' %}">BESTBUY</a>
    <a href="{% url 'basic_app:ebay' %}">EBAY</a>
    <a href="{% url 'basic_app:google' %}">GOOGLE</a>
    <a href="{% url 'basic_app:yahoo' %}">YAHOO</a>
  </body>
</html>